### ISSUE TITLE
Wie skalierbar ist das System? Wie viele User/Notifications sind möglich?

### ISSUE THREAD

**Issue by jacobchromy** [lipp/node-jet#11]

**Comment by lipp** [comment]
@jacobchromy kann ich das issue erstmal schliessen?

**Comment by jacobchromy** [comment]
Ja ☺

Von: Gerhard Preuss [mailto:notifications@github.com]
Gesendet: Dienstag, 5. Mai 2015 13:05
An: lipp/node-jet
Cc: Jacob Chromy
Betreff: Re: [node-jet] Wie skalierbar ist das System? Wie viele User/Notifications sind möglich? (#11)


@jacobchromy<https://github.com/jacobchromy> kann ich das issue erstmal schliessen?
