### ISSUE TITLE
default access groups to "all"

### ISSUE THREAD

**Issue by markert** [lipp/node-jet#61]
If a setGroup is defined and no fetchGroup, the state is not visible without logging in. 

```javascript
var state = new jet.State('xyz', {val: true}, {setGroups: ['device']});
state.on('set', jet.State.acceptAny);
peer.add(state);
```
I would expect that this state is fetchable by everyone but setable only by the user 'device'.

**Comment by lipp** [comment]
correct. i'll change it.
