### ISSUE TITLE
fetchGroups with callGroups

### ISSUE THREAD

**Issue by markert** [lipp/node-jet#63]
fetchGroups do not seem to work for methods. Every peer can fetch all methods even without logging in.

**Comment by lipp** [comment]
can you provide an example?
The tests pass. Here a Method is added:
https://github.com/lipp/node-jet/blob/master/test/authentication-tests.js#L121

and here the method is NOT visible:
https://github.com/lipp/node-jet/blob/master/test/authentication-tests.js#L155

So everything seems to be ok/

**Comment by lipp** [comment]
@markert ping?!

**Comment by markert** [comment]
My mistake. I defined a setGroup instead of a callGroup. Since a path can describe either a method or a state, I do not see, why there must be a distinction between setGroups and callGroups. I guess it would be sufficient to define two types of groups. Those, who can fetch and those, who can call/set.

**Comment by lipp** [comment]
yes. from implementation point of view this is even easier. 
i just could not find a suitable name xxxGroup. suggestions?

**Comment by markert** [comment]
Maybe:

fetchGroup -> readGroup
callGroup/setGroup -> writeGroup

**Comment by lipp** [comment]
i don't like this too much because the relationship between the matching call/message name ('set', 'call', 'fetch') get lost.
