### ISSUE TITLE
Advise about persistence with node's cluster ?

### ISSUE THREAD

**Issue by moshir** [lipp/node-jet#71]
On a single node, I guess the obvious way to persist states is to attach a fetcher server side and save whatever comes in.
When using node's cluster module, one might declare N fetchers listening for the same events, and receiving  the same events, hence leading to save the same 'docs' in turn.

What would you do in this case ?
I'm sure there's a smart way to handle this. but don't seem to get it.

**Comment by moshir** [comment]
In fact, its up to the app to make sure each worker subscribes to the appropriate paths.

**Comment by lipp** [comment]
This is an interesting, I think. You are right, it's up to the application / user.
There are some solutions which seem reasonable to me.

a) As you suggested: 
   Setup up multiple fetchers, e.g. 24 fetcher for all characters to distribute persistency to n 1..24 nodes:
   
```javascript
// node1.js  
var personsStartingWithA = new jet.Fetcher()
  .path('startsWith', 'persons/a')
   .pathCaseInsensitive()
   .on('data', store.persist); // store to db

 peer.fetch(personsStartingWithA);
```

 ```javascript
// node2.js 
var personsStartingWithB = new jet.Fetcher()
  .path('startsWith', 'persons/b')
  .pathCaseInsensitive()
  .on('data', store.persist); // store to db

peer.fetch(personsStartingWithB);
```

b) Distribute the persistency within each state's (doc's) __set__ callback, e.g. based on path:

```javascript
var personA = new jet.State('persons/adjahs', {name: 'jim', age: 24});
personA.on('set', function(newValue) {
  if (validatePerson(newValue)) {
    remoteDB1.store(newValue);
  }
});

var personB = new jet.State('persons/bdjsha', {name: 'james', age: 33});
personB.on('set', function(newValue) {
  if (validatePerson(newValue)) {
    remoteDB2.store(newValue);
  }
});
