### ISSUE TITLE
secured web socket

### ISSUE THREAD

**Issue by moshir** [lipp/node-jet#85]
I have a serious integration issue.
I'm using nginx in front of my web app an ssl is enabled.
Now, I have a Mixed Content error on the client because the page is retrieved using https while the client connects using ws url.
It seems it is not pssible to connect to a non secured web socket server from an https page.

I also tried to see if node-jet could connect using an https server and have a peer connect using wss urls but it doesnt work.

In the node-jet code repository, there are no mention of wss at all so it seems it is not supported.

I would very much appreciate any clue on this issue.
Is there any support I'm not aware of for secured web sockets in node-jet.

Thank you.

**Comment by lipp** [comment]
thanks for reporting. yes, when serving https, cou cannot connect to ws:// protocol.

ssl is neither implemented nor tested yet. however - as node-jet uses [ws](https://github.com/websockets/ws) websocket implementation - this should be no biggy.
PR welcome :)

**Comment by lipp** [comment]
Wss works transparently with ws. Just pass in a server configured for ssl / https:

```javascript
		var options = {
				key: fs.readFileSync('test/fixtures/key.pem'),
				cert: fs.readFileSync('test/fixtures/certificate.pem')
			};
			server = https.createServer(options, function (req, res) {
			 ...
			});
			server.listen(23490);
			daemon = new jet.Daemon();
			daemon.listen({
				server: server
			});
```

for self signed certs you must specifiy this in jet.Peer ctor:

```javascript
	var peer = new jet.Peer({
				url: 'wss://localhost:23490'
				rejectUnauthorized: false
			});
```

**Comment by lipp** [comment]
@moshir as an alternative you could also tunnel all the (encrypted) Jet websocket traffic.

is this ok for you?

**Comment by moshir** [comment]
Option 1 works : you have to use : `rejectUnauthorized: false` when you create your peer.
In my case, the  nice thing is you can leave encryption in **nginx** and have node.js and jet daemon unsecured.
